### ISSUE TITLE
Output is empty

### ISSUE THREAD

**Issue by sylvainmouquet** [osv/sql-formatter-cli#13]
Hello,

I use this script : `find database-schema -name *.sql -exec sql-formatter-cli -i {} -o {} \;`
I run the script in a git precommit step.
Randomly , the output file is empty. Have you ideas why the output could be empty file and how to prevent it ? 

Thanks

**Comment by sylvainmouquet** [comment]
i move to the project `https://github.com/zeroturnaround/sql-formatter`

**Comment by osv** [comment]
Yes, make sense
