### ISSUE TITLE
There is wrong link to the github url for project on NPM Site

### ISSUE THREAD

**Issue by prabodhmeshram** [osv/sql-formatter-cli#3]
As I was going through this amazing utility, I wanted to extend the functionality a bit but was ard time finding the GitHub repository link on npmjs.com.

There seems to be some wrong url in the repository link for this project.

Can you please update that @osv 

Thanks

**Comment by osv** [comment]
Thanks, url is fixed.
Keep in mind that this is just client to lib sql formatter

**Comment by prabodh-meshram-avalara** [comment]
Yeah, I saw that, Its just a wrapper around the original sql formatter. Very neat one can be extended to support more features.

**Comment by prabodhmeshram** [comment]
Yeah, I know its a wrapper over the original sql formatter, can be extended to support more features.
