### ISSUE TITLE
Handling of comments seems broken.

### ISSUE THREAD

**Issue by larsks** [osv/sql-formatter-cli#4]
Given the following SQL:

```
-- This is the first statement
select * from foo where color = "purple";

-- This is the second statement
select * from foo join bar on foo.id = bar.foo_id where bar.count > 100;
```

`sql-formatter-cli` produces the following output:

```
-- This is the first statement
select
  *
from
  foo
where
  color = "purple";-- This is the second statement
select
  *
from
  foo
  join bar on foo.id = bar.foo_id
where
  bar.count > 100;
```

Note how the second comment has been appended to the final line of the
previous SQL statement. That seems erroneous. If there were an option
to preserve whitespace (such as the blank line separating the second
comment from the previous statement), this would probably be correct.

**Comment by osv** [comment]
Hi, lets wait when this one will be closes.. 
https://github.com/zeroturnaround/sql-formatter/issues/50

**Comment by circld** [comment]
looks like some progress has been made (although this isn't yet part of a release):
https://github.com/zeroturnaround/sql-formatter/pull/58

**Comment by osv** [comment]
still waiting for relese

**Comment by ihateids** [comment]
nice work, but without working comments it is not fully usable :(

**Comment by osv** [comment]
@larsks , @ihateids Now this pkg use dependency sql-formatter 2.3.3, sample above is formatted next way:

```
-- This is the first statement
select
  *
from
  foo
where
  color = "purple";
-- This is the second statement
select
  *
from
  foo
  join bar on foo.id = bar.foo_id
where
  bar.count > 100;
```

You need to install new 2.3.3 version `npm i -g sql-formatter-cli`
